### ISSUE TITLE
Watch and rebuild  when presets/mixins changes

### ISSUE THREAD

**Issue by MikeBild** [untool/untool#117]

**Comment by dmbch** [comment]
@MikeBild what kind of scenario do you have in mind?

**Comment by ZauberNerd** [comment]
To have "hot-reload" during development on a mixin

**Comment by dmbch** [comment]
IRL, we agreed not to tackle this topic within `untool` at this point - the required specific functionality is being added downstream in https://github.com/xing/hops/pull/590.

Feel free to reopen if you still think we should change our minds in this regard.
