### ISSUE TITLE
Expose runtime render/bootstrap the same way as core/bootstrap

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#143]
With untool/core we can use `bootstrap` to quickly create a mixinable container and call defined mixin methods on this container.
Unfortunately this only works for core mixins.

I need to be able to access `getApolloCache` from the `hops-graphql` package and therefore have hacked the following code:

```javascript
import { environmentalize } from '@untool/core/lib/env';
import { getConfig } from '@untool/core/lib/config';
import define from 'mixinable';

process.env.UNTOOL_NSP = 'hops';
const bootstrap = (configOverrides = {}) => {
  const config = environmentalize(getConfig(configOverrides));
  const mixins = config.mixins.server.map((mixin) => require(mixin));
  const strategies = mixins.reduce(
    (result, mixin) => ({ ...result, ...mixin.strategies }),
    {}
  );
  return define(strategies, mixins)(config);
};

const mixinContainer = bootstrap((config) => {
  config.mixins = ['hops-graphql'];
  return config;
});
```

Maybe we could make it so that `bootstrap` has two arguments `bootstrap(configOverrides, mixinType)` where `mixinType` can be one of `browser | server | runtime` or something similar instead of hardcoding `server`.

Also: Not sure if this is actually a good idea, because some mixins contain code that needs to be run through webpack before it can be used..

Usecase: I need to run this in jest in order to have access to the correctly configured fragment matcher of hops-graphql.

**Comment by dmbch** [comment]
I will have to think about this a bit - apart from your own doubts, I do not exactly love the fact that this would (obviously) only word in a node environment and we tend to keep runtime stuff universal wherever possible.

Anyway, I can imagine adding code very similar to what you proposed as a test-only utility export.

**Comment by dmbch** [comment]
@ZauberNerd would it not be possible to use/test (an instance of) your Mixin directly, i.e. without container, and just mock the methods and config values you are actually using? I.e. monkey-patch the instance you are testing?

**Comment by ZauberNerd** [comment]
@dmbch yes, I think something like that is more robust - or maybe even just implement the logic needed for the test helper yourself. All other things would potentially break if webpack-isms are used in some of the mixins and therefore would require a webpack build.
