### ISSUE TITLE
Webpack configs

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#160]
Just a quick thought:

Would it make sense to combine the `develop` and `build` configs into one and use conditionals to include / enable / disable certain plugins for each use-case (eg Split Chunks Plugin, HMR Plugin, Uglify Plugin, etc).

Then we wouldn't have to maintain two separate configs which are mostly identical and the separation between Node / Browser would be easier to understand.

**Comment by dmbch** [comment]
I just tried this - and unfortunately, there are still quite a lot of differences between the two configs. Doing what you propose would therefore mean making the Webpack mixin quite a bit larger and, in my opinion, quite unreadable.

I will therefore close this for now. Please reopen if you disagree. :smile:
