### ISSUE TITLE
Should @untool/react have @babel/core@7 as direct dependency?

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#220]
I'm getting a couple of errors, when installing a new project, because `@babel/preset-react` has a peer dependency to `@babel/core`.

I don't think the downstream project should have to install `@babel/core` directly, because they don't use it in their applications.
Therefore I suppose that `@untool/react` should bring its own `@babel/core`.

Skimming through the code, it looks like `@untool/webpack` also has a direct dependency to `@babel/core`, same goes for `jest-preset-hops`.
On the topic of Hops: `hops-react` also adds babel plugins which have peer dependencies to `@babel/core`, therefore, both, `@untool/react` and `hops-react` should bring their own `@babel/core` I think.

**Comment by dmbch** [comment]
I completely agree: `@untool/react` should definitely include `@babel/Core` as a dependency.
