### ISSUE TITLE
Allow more maintainers to release untool

### ISSUE THREAD

**Issue by robin-drexler** [untool/untool#238]
Currently, only @dmbch, @ZauberNerd and my humble self are in the admin team of this repository and hence capable of releasing untool.

I think, we should add more people, namely @herschel666 and @jhiode to this `admin` team.

It seems, I can't do it as I'm not an org admin.

I'm well aware that a CI step to release would be adventurous, but since we don't have that yet, I'd argue allowing more people to release is a good workaround for now.

**Comment by dmbch** [comment]
Done.
