### ISSUE TITLE
importComponent breaks in production with re-exported modules

### ISSUE THREAD

**Issue by toomuchdesign** [untool/untool#240]
This issue was opened in [Hops repo](https://github.com/xing/hops/issues/758), this is its follow-up.

[untool/react](https://github.com/untool/untool/blob/master/packages/react/lib/render.js#L11) iterates over a `moduleFileMap` object which contains a few **invalid keys** (`""` and `null`) when:

- Webpack's [**ModuleConcatenationPlugin**](https://webpack.js.org/plugins/module-concatenation-plugin/) is introduced in production mode by [untool/webpack](https://github.com/untool/untool/blob/7c9fa25a97804dc5b47aea4135719ac04daffb9d/packages/webpack/lib/configs/build.js#L132).
- User dynamically import re-exported modules

It seems to be a known [webpack semi-issue](https://github.com/webpack/webpack/issues/8062), in relation to which Webpack's maintainer suggested to use an alternative way to identify generated modules.

**Avoiding** to **spread non-iterables** entities [here](https://github.com/untool/untool/blob/7c9fa25a97804dc5b47aea4135719ac04daffb9d/packages/react/lib/render.js#L10) seems to fix the issue (but I couldn't guarantee about possible side-effects 😃):

```js
  const moduleFiles = modules.reduce(
    (result, module) => {
      const moduleFile = moduleFileMap[module] || [];
      return[...result, ...moduleFile]; 
    },
    []
  );
```

**Comment by dmbch** [comment]
Hey @toomuchdesign, thanks for this issue and for your investigation. I decided to focus on the `StatsPlugin` based solution proposed by @ZauberNerd here, as it appears to tackle the root cause. Other than that, your approach is certainly equally valid.

**Comment by dmbch** [comment]
By the way, things *might* have changed since Tobias' commented on the Webpack issue you linked to - at least in our config, instances of `ConcatenatedModule` do have an id field... 🤷‍♂️
