### ISSUE TITLE
Make importComponent work in test environments

### ISSUE THREAD

**Issue by robin-drexler** [untool/untool#268]
I tried to implement support for `importComponent`  in test frameworks such as jest in hops.
While I had fun creating it, [the resulting babel-plugin](https://github.com/xing/hops/commit/80af95a82d7e9b40f8a95068371d73c847248015) to "fix" the below mentioned issues has as many locs as the original `importComponent`'s babel plugin. 

It does not work out of the box, because `importComponent` relies on wepback being present.([`require.resolveWeak`](https://github.com/untool/untool/blob/master/packages/react/lib/babel.js#L39-L40) and [`__webpack_modules__`](https://github.com/untool/untool/blob/master/packages/react/lib/runtime.js#L46)) are the ones in particular causing issues.

The `__webpack_modules__` error (` ReferenceError: __webpack_modules__ is not defined`) should be fixable by checking for its existence before accessing a value.

For `require.resolveWeak`, I suggest to add a `test` option to the babel plugin which will simply replace the `require.resolveWeak` with a `0` as `moduleId`. Afaik this should not cause any issues.

There's another issue, because the `importComponent` plugin adds an `import` statement which then won't be handled by `babel-plugin-dynamic-import-node`.  The following error is thrown instead: `Jest encountered an unexpected token` I tried to shuffle plugins around, but to no avail. I suppose it's some race condition? tbh I wonder how such issues don't happen more regularly with babel plugins, but I might just not understand them well enough yet.

Maybe we could also use `Promise.resolve(require('whatever'))` instead of using `import` when the `test` flag is passed?

**Comment by dmbch** [comment]
@robin-drexler, while we have almost certainly discussed this before, could you be so kind as to explain why we cannot mock `importComponent` entirely and without transpilation?

Example:
```javascript
const mockImportComponent = (path, name = 'default') => require(path)[name]
```

**Comment by robin-drexler** [comment]
@dmbch afaik `importComponent`'s api is a bit more flexible than just passing a path and an optional name. For example you can provide [a custom `loader`] prop (https://github.com/untool/untool/blob/master/packages/react/lib/runtime.js#L53) to the returned Component.

I'd like to have the mock resemble the real thing as closely as possible.
We could create a mock hoc that returns the actual [`Importer`](https://github.com/untool/untool/blob/master/packages/react/lib/runtime.js#L39) (if  that was available and we'd add a guard around `__webpack_modules__`)

**Comment by dmbch** [comment]
@robin-drexler I am not quite sure I understand the goal here: one could easily test both `loader` and `render` separately, right? And those props would not be used anyway...

**Comment by robin-drexler** [comment]
The goal is simply to keep the code that is run in tests as real as possible. Imo any mocking comes with a cost, especially if it's done implicitly and without any knowledge of the consumer. 

> one could easily test both `loader` and `render`

Yes, but it should in my opinion also be possible to the entire thing in its full beauty

> And those props would not be used anyway...

Why wouldn't they? If I see it correctly, loading will `indeed` be used, because `state.loading` will initially be true: https://github.com/untool/untool/blob/master/packages/react/lib/runtime.js#L49

**Comment by dmbch** [comment]
@robin-drexler I am still not convinced, really: in a Node.js environment, `loading` will never be `true`, so we will not be closer to reality if we do what you propose, as far as I can tell.

Let us see what the rest of @untool/core are saying, shall we?

**Comment by robin-drexler** [comment]
The default jest environment is a dom-ish one, so I'd go with that as default.
I did not want to go as far as to detect the env we run in and behave differently based on that. 

In any case an incomplete mock would already be an improvement to simply failing as soon as `importComponent` is used. Which is what currently happens.

**Comment by dmbch** [comment]
I would say we ought to add the incomplete/minimal mock for now and iterate/enhance it if and when necessary. Should we add that mock here or over in `xing/hops`? Both options appear to have certain merits.

**Comment by herschel666** [comment]
I'd also go for the minimal implementation because this function has — if I get this right — three features worth testing.

1. the actual inserting of an asynchrously loaded component
2. the displaying of a given loading state
3. the displaying of a given error state

Since we can I only provide one of those features deterministically inside test runs at a time, I would go with the first one: have the function do its basic job and not stand in the way of people wanting to test their application. For displaying optional loading or error states, peeps can easily roll their own mocks.

And since Hopsland is the realm of the Jest _verlötung_ I'd add this mock function over there.

**Comment by herschel666** [comment]
As discussed during the standup today, we'll go with the minimal approach implemented in Hops.
