### ISSUE TITLE
@babel/polyfill polyfills resolve to wrong `core-js` version on compile time

### ISSUE THREAD

**Issue by toomuchdesign** [untool/untool#297]
This issue is a follow-up of https://github.com/xing/hops/pull/819.

@untool/webpack relies on [`@babel/present-env`'s `useBuiltIns` feature](https://babeljs.io/docs/en/babel-preset-env#usebuiltins) which [might break](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry) when the globally hoisted `core-js` version doesn't match the one expected by `@babel/polyfill`.

## Solution 1: `core-js` as peer dependency
A solution might consist of declaring `core-js@^2` as `@untool/webpack`'s peer dependency to force the consuming application to keep it as it's own direct dependency

## Solution 2: `core-js v2` dependency check on build
On compile time`@untool/webpack` might ensure that the expected version of `core-js` is available at `node_modules` root and issue a warning message if not.

## Solution 3: custom module resolution
Extend the current custom module resolution to target the polyfill declaration injected by babel and redirect them to the expected `core-js` library.

**Comment by dmbch** [comment]
I think I will go with solution 2 - PR forthcoming.

**Comment by bxt** [comment]
@dmbch How is this supposed to work? A `yarn add core-js@2` solved the problem for me, but I had to bascially Google and click through some GitHub issues to get here. I think there should be some kind of warning?

I just set up a fairly basic Hops project and once I added code splitting I got a lot of errors like this:

```
ERROR in: (webpack)/buildin/global.js
Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/Users/bernhardhaussner/xing/grow-frontend/node_modules/webpack/buildin'
 @ (webpack)/buildin/global.js 1:0-52
 @ ./node_modules/stream-http/index.js
 @ ./node_modules/eventsource/lib/eventsource.js
 @ ./node_modules/@untool/webpack/lib/shims/develop.js
```

Using:

```
$ yarn list --pattern '@untool|core-js'
yarn list v1.10.1
├─ @babel/polyfill@7.4.0
│  └─ core-js@2.6.5
├─ @untool/core@1.5.1
├─ @untool/express@1.5.1
├─ @untool/react@1.5.1
├─ @untool/webpack@1.5.1
├─ @untool/yargs@1.5.1
├─ core-js-compat@3.0.0
│  └─ core-js@3.0.0
├─ core-js-pure@3.0.0
└─ core-js@1.2.7
```

And I think no specific warning?

**Comment by dmbch** [comment]
@bxt we are currently still in the process of integrating `@untool/info` [downstream, i.e. in `hops`](https://github.com/xing/hops/pull/838). When that has happened, we will have a warning inplace.

Sorry for the inconvenience.

**Comment by bxt** [comment]
Ah I see thank you for the quick answer. I was confused because I already used the latest untool version and I did not know it also requires some changes to hops to make it work. Thanks!
