### ISSUE TITLE
un-opinionate untool 

### ISSUE THREAD

**Issue by robin-drexler** [untool/untool#42]
We've figured that untool should do less and leave the more specific implementations to other projects, such as https://github.com/xing/hops.

In this ticket we'll try to collect concerns that untool could care less about: 

- express compress middleware 
- static rendering?
- postcss / css config 
- isESNext/isExternal ?
- react

**Comment by matthias-reis** [comment]
- defaults package?
- express helmet mw?
- react +1
- additional babel presets ?
```
      plugins: [
        // require.resolve('babel-plugin-syntax-dynamic-import'),
        require.resolve('babel-plugin-transform-class-properties'),
        require.resolve('babel-plugin-transform-object-rest-spread'),
      ],
```
- css +1
- yargs log

**Comment by jhiode** [comment]
css +1
yargs log +1
config env

Despite that I would suggest to not remove the other mentioned features but rather try to make them even easier to extend / override.

**Comment by ZauberNerd** [comment]
Express config:
- Default `locations` to `[]`
- Rename `ip` to `host`
