### ISSUE TITLE
[RFC]: Secrets in environment variable placeholders

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#446]
We've discovered that there is a need to specify which config values should be sent to the client / or which values contain secrets and should therefore only be exposed to the server-side implementation.

There are a few solutions for white-listing values for the front-end that come to mind:
1. indicate through a naming scheme of the key, that this value should be secret (eg. `_foo`)
2. indicate through special characters in the value (eg. double brackets `[[FOO]]`) that this value should be secret
3. use an array with white-listed keys, that will be merged automatically (to allow each preset to add their own values) to indicate which values should be forwarded to the client
4. use an object that holds a mapping of keys to boolean values that should be white-listed (in contrast to the previous suggestion, this would allow users to override values set by presets)
5. allow an object as value that contains two fields (`value` and `expose` or similar) to configure that specific field

```json
{
  "name": "untest",
  "license": "MIT",
  "untool": {
    "_variant_1": "[SECRET]",
    "variant_2": "[[SECRET]]",
    "variant_3": "[NO_SECRET]",
    "whitelist_array": [
      "variant_3"
    ],
    "variant_4": "[NO_SECRET]",
    "whitelist_object": {
      "variant_4": true
    },
    "variant_5": {
      "value": "[NO_SECRET]",
      "expose": true
    }
  }
}
```

**Comment by dmbch** [comment]
Another option would be to introduce an object (e.g. `serverOnly`) that would be merged and generally handled separately and that could hold the appropriate props and hidden from the client.

That being said, my personal preference would be option 1 or 2..: these appear to be most aligned with framework and ecosystem standards and conventions.

**Comment by ZauberNerd** [comment]
I would prefer to white-list keys that should go to the client-side instead of black-listing them (which would be kind of the case with `serverOnly`).

I don't like variant 2 and 5 because then a user could overwrite the default value that comes from a preset and would lose the visibility settings.

With variant 1 we would need to change our code whenever the visibility changes (or build some complicated getter/proxy stuff around it), therefore I would prefer variant 3 or 4.
I think I'm leaning more towards variant 4, because that would allow later presets / the application config to overwrite the visibility of values, but since it will always be merged it is safe by default.

**Comment by herschel666** [comment]
I mostly agree with @ZauberNerd here. I would add though that version 4 makes it too easy to overwrite the setting and thus provides kind of a foot gun. I also right now can't think of a situation where a preset would want to change the visibility set by a previous preset.

So I'd be in favour of variant 3.

It still provides a way to change the setting, which could be applied by users and preset authors alike. So coming from a preset that looks like that…

```json
{
  "secret": "[SUPER_SECRET]"
}
```

…ppl could expose the value like this…

```json
{
  "secret": "[SUPER_SECRET]",
  "meDontCares": "<secret>",
  "whitelist_array": ["meDontCares"],
}
```

**Comment by dmbch** [comment]
If we did decide to go with variant 3, we would have to deal with that array similar to [`mixins`](https://github.com/untool/untool/blob/master/packages/core/lib/utils.js#L39) - and that would be breaking abstractions, unfortunately: we would be introducing knowledge about the distinction between client and server to `@untool/core` - and that is something it is not really supposed to know about.

I would therefore prefer going with variant 4 and implement it in `@untool/webpack`.

**Comment by herschel666** [comment]
I consider this decided & done!
