### ISSUE TITLE
[RFC]: default values in config placeholders for environment variables

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#448]
With an increasing usage of environment variables in the configuration, it might make sense to look at how we could specify default values for them.

In my opinion the preferred approach would be to have some kind of syntax in the value field:

```json
{
  "name": "untest",
  "license": "MIT",
  "untool": {
    "apiURL": "[API_URL='https://api.com']"
  }
}
```

**Comment by dmbch** [comment]
I like this idea and we actually had this sometime early on. I would get rid of the quotes, though, as env vars are also always strings.

**Comment by bxt** [comment]
... but then what if you want `[]` in the default value? Maybe (I don't know wether its possible) the bash could be used to build the string, as it can already do things like `${API_URL:-https://api.com}`, `${API_URL:?"Please specify the URL to super API serivce"}` etc. and the syntax should be familiar to some already.

**Comment by KnisterPeter** [comment]
What about adding a default object next to the untool key? That way there would be no escaping and no parsing, just a lookup.

**Comment by dmbch** [comment]
@bxt I don’t think that that will work since we are reading from `process.env` here - no bash involved.

**Comment by dmbch** [comment]
@KnisterPeter that will only work within `package.json`, but not in [other places](https://github.com/untool/untool/blob/master/packages/core/README.md#configuration) `untool` uses for configuration.

Additionally, I personally quite like the idea of keeping the env variable references and default values close to one another.

**Comment by ZauberNerd** [comment]
Relevant PR: https://github.com/untool/untool/pull/453

**Comment by ZauberNerd** [comment]
This has been merged into the next branch.
