### ISSUE TITLE
Make middleware usage independent from load order

### ISSUE THREAD

**Issue by jhiode** [untool/untool#47]
## Problem:

Right now all middlewares are registered in the same order as the mixins are loaded.
This prevents users from overriding the order without losing the benefit of presets.
It is also not possible for a user to remove a middleware.

## Solution (proposal):

Define a `registerMiddleware(s)` hook (strategy: sequence) that collects all middlewares from all mixins first and in another step read the config for the set of middlewares that is desired. This would also allow a user to ignore/remove a middleware later on.
This requires that all mixins name their middlewares.

### Example:
Mixin:
```
registerMiddlewares() {
  return {
    'my-middleware': (app) => (req, res, next) => {
      ...
    },
  }
}
```
Config:
```
{
  middlewares: [
    'my-middleware',
  ],
}
```

P.S.: Yes, middlewares is a word 😄

**Comment by dmbch** [comment]
I think I see your point, but (as mentioned IRL), I am afraid I am not quite convinced we need to change as much in `@untool/express` as you propose. Why can we not just add one or two hooks (e.g. `optimizeServer`) and rely on express' middleware chaining, e.g.:

```javascript
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');

module.exports = {
  initializeServer(app) {
    app.use(cookieParser(), bodyParser(), (req, res, next) => {
      console.log(req);
      next();
    });
    return app;
  }
}
```

That would, to my mind, mean we have two sorting dimensions (preset/mixin order and hook calling order) plus manual middleware sorting. Combined with a nice organisation of mixins/middlewares into packages we ought to be able to tackle all middleware registration requirements I personally can think of... We should probably make sure we expose all mixins/middlewares consumers might want to reshuffle in our downstream (ahem, [hops](https://github.com/xing/hops/tree/next)) packages.

Of course, we cannot enable mixins to get rid of middlewares registered by other mixins, but I am not even sure we should support that - Express.js itself does not as far as I can tell.

@jhiode are there any specific use-cases that we really cannot support with what we have and cannot easily add..? Please excuse me if I am being thick, here. 😉

**Comment by robin-drexler** [comment]
@dmbch +1 for keeping it as simple as possible and not adding another sorting dimension if we can avoid it.

The `app.use` approach looks fine, although I can imagine issues arising once the same middleware is used by multiple mixins.

This might not be much of a problem for middlewares such as `cookie-parser` where the only downside is a tiny performance penalty. However, there are also middlewares that take care of logging or authentication, where multiple execution could lead to unwanted results.

That being said, I'm not entirely sure how often that will actually occur with those middlewares, but I still wanted to voice that concern.

**Comment by dmbch** [comment]
@robin-drexler I do see your point wrt logging/error handling - that is why I am proposing an ‘override’able ‘finalizeServer’ hook.

Other than that, I would like to push the issue downstream, i.e. where requirements are less cloudy and can be addressed in a more specific manner.

With regards to a custom middlewares, we could just build them in a way that makes them run only once..:

‘’’javascript
(req, res, next) => {
  if ('user' in res.locals) return next();
  // do the usual auth dance
}
‘’’

As you already said, this approach will not help us with external middlewares, but I am sure we can come up with something...

**Comment by dmbch** [comment]
Having thought about this a bit more - and having been pointed to what others are doing by @ZauberNerd, what do you think of a single hook working essentially like this:

```javascript
const configureExpress = (app, middlewares, phases) => {
  app.use((req, res, next) => next());

  middlewares.intial = (req, res, next) => next();

  middlewareOrder.unshift('preinitial');
  middlewares.preintial = (req, res, next) => next();

  return app;
};
```

We could start by having the same phases [Strongloop](https://loopback.io/doc/en/lb3/Defining-middleware.html#middleware-phases) has and add other phases on the fly. So, the `middlewares` object would look something like this:

```javascript
{
  initial: [],
  session: [],
  auth: [],
  parse: [],
  routes: [],
  files: [], // contains static and webpack dev middlewares
  universal: [], // contains the transpiled React middleware
  final: []
}
```

I am convinced we would go further down this nice rabbit hole if we try moving things like middleware order into config, so I would really like to keep this things runtime-y. What do you think?

**Comment by ZauberNerd** [comment]
I don't think we need that many phases right now because untool itself doesn't use that many.
I'd propose something like:
- initial (for bootstrapping things)
- parse (for cookie/body parser)
- routes? (do we have "routes" as such? or is it all handled in the universal react middleware)
- files (for static file serving)
- universal (for our react render middleware)
- final (for error handling and such)

Also: The code snippet above doesn't make sense with what you wrote - could you take another look and edit it please?

**Comment by dmbch** [comment]
@ZauberNerd PTAL
