### ISSUE TITLE
Remove "browsers" from config and use "browserslist" directly

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#77]
[Browserslist is used by many different tools](https://github.com/browserslist/browserslist#browserslist-) and therefore we should remove the field `"browsers"` from our config and instead use the `browserslist` API directly because that allows our consumers to define their browsers list in [any of the supported](https://github.com/browserslist/browserslist#queries) ways and ensures that other tools may also use the specified browsers list.

**Comment by dmbch** [comment]
Both [`babel-preset-env`](https://babeljs.io/docs/en/next/babel-preset-env.html#browserslist-support) and [`postcss-preset-env`](https://github.com/csstools/postcss-preset-env#browsers) (used downstream) natively rely on `browserslist`, so we only have to remove our own config, apparently.

**Comment by dmbch** [comment]
`babel-preset-env` will apparently only start supporting `browserslist` as described above starting in version 7. It appears we would have to deep-require `browserslist/node` and use its [internals helpers](https://github.com/browserslist/browserslist/blob/master/node.js#L154) to make this work now.

**Comment by dmbch** [comment]
Closing (see #79 for reasoning).
