### ISSUE TITLE
basePath, assetPath confusion

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#81]
Just a quick thought I had while working on the pwa preset:
We might want to default `basePath` (and maybe `assetPath` too) to `/` and not allow empty strings.
Then we could always join them as url parts and don't have to think about whether they need to start with or without slash.

TODO: flesh out this idea into a concrete usage example.

**Comment by dmbch** [comment]
> TODO: flesh out this idea into a concrete usage example.

Please do! I would appreciate to understand what issues you are tackling here.

I must admit I am not too keen on changing the current behaviour, as we would have to think the different use cases throughout rather thoroughly ("absolute" paths for use in URLs, "relative" paths for Webpack etc.). Aside from that, we would still have to make sure there are no duplicate slashes (`//`) and such while joining.

**Comment by dmbch** [comment]
I'll close this for now - please reopen if you still feel we need to tackle this.
