### ISSUE TITLE
Does it make sense that webpack's "develop" command has a "static" option?

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#83]
I'm currently reviewing / writing readme documentation and I wondered whether the `--static` option for the `development` command makes sense at all as it seems that `--static` is only used when executing `build`?
https://github.com/untool/untool/blob/master/packages/webpack/mixin.core.js#L192

**Comment by dmbch** [comment]
I do not think we (technically) need it any more - it really does nothing IIRC.
